application: fofou
version: 1
runtime: python
api_version: 1

handlers:
- url: /images/([^/]+)/(.*)
  static_files: skins/\1/images/\2
  upload: skins/[^/]+/images/.* 
  
- url: /static/([^/]+)/(.*)
  static_files: skins/\1/static/\2
  upload: skins/[^/]+/static/.*  
  
- url: .*
  script: main.py

